baseURL: https://blog.razyang.com/
#defaultContentLanguage: zh
#languageCode: zh-cn
title: Misc
theme: PaperMod
params:
  defaultTheme: dark
  showtoc: true
  tocopen: true
  UseHugoToc: false
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  homeInfoParams:
    Title: Hi
    Content: Be Easy
menu:
  main:
    - identifier: archives
      name: archives
      url: /archives
    - identifier: tags
      name: tags
      url: /tags
